## CONSTANTS ##
#: minimum width and height of images 
PIXEL_WIDTH_THRESHOLD = 700
PIXEL_HEIGHT_THRESHOLD = 700

#: experimental setup constants
NUMBER_OF_PARTICIPANTS = 50
NUMBER_OF_UNIQUE_RUNS = 8
NUMBER_OF_SHARED_RUNS = 1
UNIQUE_IMAGES_PER_UNIQUE_RUN = 56
SHARED_IMAGES_PER_UNIQUE_RUN = 8
SHARED_IMAGES_PER_SHARED_RUN = 64

CROPPED_IMAGE_LIMIT = NUMBER_OF_PARTICIPANTS * NUMBER_OF_UNIQUE_RUNS * UNIQUE_IMAGES_PER_UNIQUE_RUN + SHARED_IMAGES_PER_UNIQUE_RUN*NUMBER_OF_UNIQUE_RUNS + SHARED_IMAGES_PER_SHARED_RUN

#: the names of the database root directories
FIGRAM_DATABASE_KEY = "SCENES_700x700"
SUN_DATABASE_KEY = "SUN397"